*** 🌟 Qu’est-ce que NumPy ?  ***

    NumPy (Numerical Python) est une bibliothèque qui permet de manipuler facilement des tableaux (arrays) et de faire des calculs mathématiques rapides sur de grandes quantités de données.
    
*** 🔧 À quoi sert NumPy ?  ***
Créer et manipuler des tableaux multidimensionnels (comme des matrices).

Faire des opérations mathématiques rapides (addition, multiplication, sinus, etc.).

Travailler efficacement avec des grandes données numériques.

Fournir des outils pour l’algèbre linéaire, les statistiques, les transformations de Fourier, etc.

In [1]:
import numpy as np 
# Créer un tableau (array)
a = np.array([1, 2, 3])
print(a)  # [1 2 3]


# Créer une matrice 2D
b = np.array([[1, 2], [3, 4]])
print(b)
# [[1 2]
#  [3 4]]




[1 2 3]
[[1 2]
 [3 4]]


*** 🐼 Qu’est-ce que Pandas ? ***
Pandas est une bibliothèque Python conçue pour manipuler, nettoyer, analyser et explorer des données, en particulier les données structurées (comme dans des tableaux Excel, des bases de données, des fichiers CSV...).

Elle repose sur NumPy pour les calculs en arrière-plan, mais elle fournit des structures de données très puissantes et flexibles.

🧱 *** Structures principales de Pandas ***
Series : une colonne de données (comme une liste avec un index)

DataFrame : un tableau 2D (comme une feuille Excel avec des colonnes et des lignes)



In [2]:
import pandas as pd 

data={
    
    "Num":[1,2,3,4,5],
    "Nom":['AAAA','BBBB','CCCC','DDDD','EEEE'],
    "Age":[25,12,40,55,11],    
    }
dataF1=pd.DataFrame(data)
dataF1



Num   Nom  Age
0    1  AAAA   25
1    2  BBBB   12
2    3  CCCC   40
3    4  DDDD   55
4    5  EEEE   11

In [17]:
import pandas as pd
# Lecture du fichier CSV avec différentes options

# 1. Charger un CSV avec un séparateur personnalisé (ici ';')
df = pd.read_csv("data.csv", sep=";")
print("DataFrame avec séparateur ';':")
print(df.head(), "\n")

# # 2. Charger un CSV sans en-tête et ajouter des noms de colonnes manuellement
# df_no_header = pd.read_csv("data.csv", header=None, names=["Name", "age","city", "Salary" ])
# print("DataFrame sans en-tête, avec noms de colonnes personnalisés:")
# print(df_no_header.head(), "\n")

# # 3. Charger un CSV en ne lisant que certaines colonnes (par exemple "Nom", "Âge", "Salaire")
# df_columns = pd.read_csv("data.csv", usecols=["Nom", "Age", "ville"])
# print("DataFrame avec certaines colonnes seulement:")
# print(df_columns.head(), "\n")

# 4. Charger un CSV en ignorant la première ligne (par exemple, une ligne de métadonnées)
df_skiprows = pd.read_csv("data.csv", skiprows=1)
print("DataFrame avec 1ère ligne ignorée:")
print(df_skiprows.head(), "\n")

# 5. Lire seulement un échantillon (par exemple, les 3 premières lignes)
df_sample = pd.read_csv("data.csv", nrows=3)
print("DataFrame avec 3 premières lignes:")
print(df_sample.head(), "\n")

DataFrame avec séparateur ';':
       Nom  Age      Ville  Salaire
0    Alice   25      Paris     3000
1      Bob   30       Lyon     2500
2  Charlie   28  Marseille     2700
3    David   40   Bordeaux     4000 

DataFrame avec 1ère ligne ignorée:
         Alice;25;Paris;3000
0           Bob;30;Lyon;2500
1  Charlie;28;Marseille;2700
2     David;40;Bordeaux;4000 

DataFrame avec 3 premières lignes:
       Nom;Age;Ville;Salaire
0        Alice;25;Paris;3000
1           Bob;30;Lyon;2500
2  Charlie;28;Marseille;2700 

